[package]
name = "toy-lisp"
version = "0.1.0"
authors = ["Trevor Saunders <tbsaunde@tbsaunde.org>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.13.0"
[dependencies]
lalrpop-util = "0.13.0"
regex = "0.2.1"
